### PR TITLE
nuget.targets removed in favor of automatic package restore

### PR DESCRIPTION
**Pull request by lnu**
thttps://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore

~~A change is need in the appveyor script~~

http://www.appveyor.com/blog/2014/03/18/about-nuget-package-restore

### CODE REVIEW

**Comment by milesibastos** [comment]
Everything looks fine!

``` bash
Tests run: 24, Errors: 0, Failures: 0, Inconclusive: 0, Time: 8.9954182 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
 
Packaging artifacts...OK
Uploading artifact NHibernate.AspNet.Identity.2.2.2.0.nupkg (21.4 KB)...OK
Uploading artifact NHibernate.AspNet.Identity.2.2.2.0.symbols.nupkg (64.4 KB)...OK
Uploading artifact source\NHibernate.AspNet.Identity\dropbox.zip (2.9 MB)...OK
Build success
```

We need see why that:
``` bash
ci/circleci — No test commands were found
```

**Comment by milesibastos** [comment]
I removed the circleci
image

**Comment by lnu** [comment]
Perfect. What's the purpose of circleci?

**Comment by milesibastos** [comment]
probably for test... and I forget to remove!
the appveyor is the main CI to this project

**Pull request merged**
